routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('validate', 'HomeController@validation');

Route::middleware(['auth', 'isVerified'])->group(function () {
    Route::get('dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::post('dashboard', 'HomeController@dashboardYear')->name('dashboard.year');

    // Category Levels
    Route::get('level2/{id}', 'HomeController@getLevel2')->name('api.getLevel2');
    Route::get('level3/{id}', 'HomeController@getLevel3')->name('api.getLevel3');
    Route::get('level4/{id}', 'HomeController@getLevel4')->name('api.getLevel4');
    Route::get('level5/{id}', 'HomeController@getLevel5')->name('api.getLevel5');

    // Edit Profile
    Route::get('edit', 'UserController@edit')->name('user.edit');
    Route::put('update/{user}', 'UserController@update')->name('user.update');

    // Data 
    Route::resource('data', 'DataController');

    // Attendance
    Route::get('attendance', 'AttendanceController@index')->name('attendance.index');
});

Route::prefix('adminBidang')->middleware(['auth'])->group(function(){
    Route::get('/', 'AdminBidangController@index')->name('adminBidang.index');
    Route::get('/grafik/{district}', 'AdminBidangController@detailChart')->name('adminBidang.detailChart');

    // User
    Route::get('approve', 'AdminBidangController@getApprove')->name('adminBidang.getApprove');
    Route::post('approve', 'AdminBidangController@doApprove')->name('adminBidang.approve');
    Route::get('ikm', 'AdminBidangController@getIKM')->name('adminBidang.getIKM');
    Route::get('ikm/{user}', 'AdminBidangController@detailIKM')->name('adminBidang.detailIKM');
    Route::put('ikm/{user}', 'AdminBidangController@updateIKM')->name('adminBidang.updateIKM');
    Route::get('ikmDelete/{user}', 'AdminBidangController@deleteIKM')->name('adminBidang.deleteIKM');
    
    // Data
    Route::get('listData/{user}', 'AdminBidangController@listData')->name('adminBidang.listData');
    Route::get('detailData/{data}', 'AdminBidangController@detailData')->name('adminBidang.detailData');
    Route::get('data/{user}', 'AdminBidangController@addData')->name('adminBidang.addData');
    Route::post('data', 'AdminBidangController@storeData')->name('adminBidang.storeData');

    // Facility
    Route::resource('facility', 'FacilityController');

    // Attendance
    Route::resource('attendance', 'AttendanceController')->except(['create', 'index']);
    Route::get('attendance/create/{facility}', 'AttendanceController@create')->name('attendance.create');
    Route::get('attendance/facility/{facility}', 'AttendanceController@facility')->name('attendance.facility');
    Route::get('attendance/product/{facility}/{user}', 'AttendanceController@product')->name('attendance.product');
});

Route::prefix('superAdmin')->middleware(['auth'])->group(function(){
    Route::get('/', 'SuperAdminController@index')->name('superAdmin.index');
    Route::get('/grafik/{district}', 'SuperAdminController@detailChart')->name('superAdmin.detailChart');
    // Admin Bidang
    Route::get('/adminBidang', 'SuperAdminController@adminBidang')->name('superAdmin.adminBidang.index');
    Route::get('/adminBidang/create', 'SuperAdminController@adminBidangCreate')->name('superAdmin.adminBidang.create');
    Route::post('/adminBidang', 'SuperAdminController@adminBidangStore')->name('superAdmin.adminBidang.store');
    Route::get('/adminBidang/edit/{user}', 'SuperAdminController@adminBidangEdit')->name('superAdmin.adminBidang.edit');
    Route::put('/adminBidang/edit/{user}', 'SuperAdminController@adminBidangUpdate')->name('superAdmin.adminBidang.update');
    Route::delete('adminBidang/{user}', 'SuperAdminController@adminBidangDestroy')->name('superAdmin.adminBidang.destroy');

    // Category
    Route::resource('/category', 'CategoryController');

    // Facility Category
    Route::get('/facilityCategory', 'SuperAdminController@facilityCategory')->name('superAdmin.facilityCategory.index');
    Route::get('/facilityCategory/create', 'SuperAdminController@facilityCategoryCreate')->name('superAdmin.facilityCategory.create');
    Route::post('/facilityCategory', 'SuperAdminController@facilityCategoryStore')->name('superAdmin.facilityCategory.store');
    Route::get('/facilityCategory/edit/{facilityCategory}', 'SuperAdminController@facilityCategoryEdit')->name('superAdmin.facilityCategory.edit');
    Route::put('/facilityCategory/edit/{facilityCategory}', 'SuperAdminController@facilityCategoryUpdate')->name('superAdmin.facilityCategory.update');
    Route::delete('/facilityCategory/{facilityCategory}', 'SuperAdminController@facilityCategoryDestroy')->name('superAdmin.facilityCategory.destroy');
});

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Attendance extends Model
{
    use SoftDeletes;
    protected $fillable = ['facility_id', 'user_id', 'product_id'];

    public function User()
    {
        return $this->belongsTo('App\User');
    }

    public function Facility()
    {
        return $this->belongsTo('App\Facility');
    }

    public function Product()
    {
        return $this->belongsTo('App\Product');
    }
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use App\Attendance;
use Illuminate\Http\Request;
use App\Facility;
use App\User;
use DB;

class AttendanceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('attendance.index');
    }

    public function facility(Facility $facility)
    {
        return view('admin.attendance.index', [
            'facility' => $facility
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Facility $facility)
    {
        $attendances = Attendance::where('facility_id', $facility->id)->pluck('user_id');
        $users = User::where('role', 'IKM')->whereNotIn('id', $attendances)->get();
        
        return view('admin.attendance.create', [
            'users' => $users,
            'facility' => $facility
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->product_id) {
            Attendance::create($request->all());
            $request->session()->flash('status', 'Data berhasil disimpan');
        }
        return redirect(route('attendance.create', ['facility' => $request->facility_id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function show(Attendance $attendance)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function edit(Attendance $attendance)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Attendance $attendance)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Attendance  $attendance
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attendance $attendance)
    {
        $attendance->delete();
        // $request->session()->flash('status', 'Data berhasil dihapus');
        return redirect(route('facility.index'));
    }

    public function product(Facility $facility, User $user)
    {
        return view('admin.attendance.product', [
            'user' => $user,
            'facility' => $facility
        ]);
    }
}

resources/views/admin/attendance/create.blade.php
@extends('layouts.app')

@push('css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endpush

@section('content')
<div class="row">
    <div class="col-xl-12 col-lg-12">
        <div class="card">
            <div class="card-block">
                @include('layouts.alert')
                <h3>Tambah Kehadiran</h3>
                <div class="row">
                    <div class="col-md-12">
                        <form action="{{route('attendance.store')}}" method="POST">
                            @csrf
                            <input type="hidden" name="facility_id" value="{{$facility->id}}">
                            <table id="myTable">
                                <thead>
                                    <tr>
                                        <th>Nama Perusahaan</th>
                                        <th>Nama Pemilik</th>
                                        <th>Alamat</th>
                                        {{-- <th>Tambah</th> --}}
                                        <th>Lihat Produksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                            <td>
                                                @if ($user->legality != 'Tidak Berbadan Hukum')
                                                    {{$user->legality}}
                                                @endif
                                                {{$user->name}}</td>
                                            <td>{{$user->owner}}</td>
                                            <td>
                                                @isset ($user->District->name)
                                                    {{$user->company_address . ', ' . $user->District->name}}
                                                @else
                                                    -
                                                @endisset
                                            </td>
                                            {{-- <td>
                                                <div class="rkmd-checkbox checkbox-rotate checkbox-ripple m-b-25">
                                                    <label class="input-checkbox checkbox-primary">
                                                        <input type="checkbox" id="checkbox" value="{{$user->id}}" name="user_id[]">
                                                        <span class="checkbox"></span>
                                                    </label>
                                                </div>
                                            </td> --}}
                                            <td>
                                                <a href="{{route('attendance.product', ['user' => $user->id, 'facility' => $facility->id])}}" class="btn btn-primary">
                                                    Lihat
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <div class="form-group">
                                {{-- <button type="submit" class="btn btn-primary full-width">Simpan</button> --}}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable();
        } );
    </script>
@endpush

resources/views/admin/attendance/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-xl-12 col-lg-12">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-9">
                        <h3>Daftar Hadir {{$facility->name}}</h3>
                    </div>
                    <div class="col-md-3">
                        <a href="{{route('attendance.create', ['facility' => $facility->id])}}" class="btn btn-success full-width">Tambah Kehadiran</a>
                    </div>
                </div>
                @include('layouts.alert')
                <div class="row">
                    <div class="col-md-12">
                        <table id="myTable" class="display">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Nama Perusahaan</th>
                                    <th>Nama Pemilik</th>
                                    <th>Alamat</th>
                                    <th>Hapus</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($facility->Attendance as $index => $attendance)
                                    <tr>
                                        <td>{{++$index}}</td>
                                        <td>{{$attendance->User->legality}} {{$attendance->User->name}}</td>
                                        <td>{{$attendance->User->owner}}</td>
                                        <td>{{$attendance->User->company_address}}, {{$attendance->User->District->name}}</td>
                                        <td>
                                            <form action="{{route('attendance.destroy', ['attendance' => $attendance->id])}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger">Hapus</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script>
        $(document).ready( function () {
            $('#myTable').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'excel'
                ]
            } );
        } );
    </script>
@endpush

resources/views/admin/attendance/product.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-xl-12 col-lg-12">
        <div class="card">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-9">
                        <h3>Daftar Produk {{$user->legality}} {{$user->name}}</h3>
                    </div>
                </div>
                @include('layouts.alert')
                <form action="{{route('attendance.store')}}" method="POST">
                    @csrf
                    <input type="hidden" name="user_id" value="{{$user->id}}">
                    <input type="hidden" name="facility_id" value="{{$facility->id}}">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Tahun</th>
                                        <th>Foto</th>
                                        <th>Nama Produk</th>
                                        <th>Tambah</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($user->Data as $data)
                                        @foreach ($data->Product as $product)
                                            <tr>
                                                <td>{{$data->year}}</td>
                                                <td><img src="{{asset('storage/'.$product->photo)}}" alt="{{$product->name}}" class="img-thumbnail" style="max-width: 100px"></td>
                                                <td>{{$product->name}}</td>
                                                <td>
                                                    <input type="radio" name="product_id" value="{{$product->id}}" class="form-control">
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-success full-width" onclick="history.go(-1);">Tambah dan Kembali Ke Halaman Kehadiran</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection